### ISSUE TITLE
flatten ignores errors reported by individual streams in a stream of streams

### ISSUE THREAD

**Issue by regular** [dominictarr/pull-stream#32]
Example Code

``` js
  pull(
    pull.values([
      pull.Source(function read(abort, cb) {
          cb(new Error('I am broken');)  
        })
    ]),
    pull.flatten(),
    pull.onEnd(function (err) {
      // err is null
    })
  )
```

**Comment by dominictarr** [comment]
Should a stream of streams go through and abort every stream? or should it just abort the stream of streams and it's that stream's responsibility to abort the individual streams. The latter. If those streams are coming from a generator, then there won't actually be a queue of them.

Since the inner stream has just errored, it only has to abort the parent stream.
(but if you get an abort, it should abort the current stream and the parent stream too)

btw, pull.values takes a second arg, `pull.values([..], onAbort)` so you can detect when it has been aborted. which is quite useful for testing.

**Comment by regular** [comment]
> Should a stream of streams go through and abort every stream? or should it just abort the stream of streams and it's that stream's responsibility to abort the individual streams. The latter.

I suppose you mean: "Should _flatten_ go through and abort every nested stream in a stream of streams ... "?

I've been thinking about this. `flatten` is the reader of the stream of streams (_s'o's_). As soon as it has read an item (= _nested stream_) from the sos, it also becomes that nested streams' reader. Because it is both, the reader of the sos and the reader of the _current_ nested stream, it is responsible to abort both of them. However, it is not (yet) the reader of the _other_ nested streams (that follow the current one) and therefor should not abort them.

If an sos has eagerly prepared a set of nested streams and queued them up, it is the sos' responsibility to abort them once itself has been aborted. (as you point out, this is normally not the case, not when the sos is lazy)

So, yes, I fully agree. I'll work on refining the PR accordingly.
